# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30, verbose_name='Menu Name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='SEO friendly URL, use alphabets and hyphen')),
                ('link', models.CharField(blank=True, max_length=20, null=True, verbose_name='Link')),
                ('active', models.IntegerField(default=2)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus_relatedto_users', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.Menus')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='RoleConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('add', models.IntegerField(blank=True, null=True)),
                ('edit', models.IntegerField(blank=True, null=True)),
                ('view', models.IntegerField(blank=True, null=True)),
                ('delete', models.IntegerField(blank=True, null=True)),
                ('search', models.IntegerField(blank=True, null=True)),
                ('report', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField(default=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roleconfiguration_related_created_user', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleconfiguration_related_menus', to='usermanagement.Menus')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roleconfiguration_related_modified_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role'],
                'verbose_name_plural': 'RoleConfiguration',
            },
        ),
        migrations.CreateModel(
            name='RoleTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Role Name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='SEO friendly URL, use alphabets and hyphen')),
                ('active', models.IntegerField(default=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roletypes_related_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'RoleTypes',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.IntegerField(default=2)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userroles_related_created_users', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userroles_related_modified_users', to=settings.AUTH_USER_MODEL)),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userroles_related_roletypes', to='usermanagement.RoleTypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'verbose_name_plural': 'UserRoles',
            },
        ),
        migrations.AddField(
            model_name='roleconfiguration',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleconfiguration_related_role_types', to='usermanagement.RoleTypes'),
        ),
    ]
